### PR TITLE
Fixed: False usage is showing on week -summary command in v1.0

### PR DESCRIPTION
**Pull request by ujjwall-R**

### CODE REVIEW

**Comment by Waishnav** [comment]
@ujjwall-R whenever you are changing some file and trying to solve issue, try to make changes in new branch to avoid future merge conflict.
Don't work on branch directly after clonning.

**Review by Waishnav — CHANGES_REQUESTED** [review]
Solve the issue, not through Brute-forcing, solve it from the root cause.

**Comment by ujjwall-R** [comment]
> Solve the issue, not through Brute-forcing, solve it from the root cause.
Can you help me find the root cause. I am unable to figure out.

**Comment by Waishnav** [comment]
Time spent in every session of the app is written accurately in the log files. The most probably issue is in the commands.py

**Comment by Waishnav** [comment]
If you are working on solving this issue then let me know.

**Comment by ujjwall-R** [comment]
No, I am not working on this issue anymore.

**Pull request closed without merging**
